model_args:
  base_model: "FacebookAI/roberta-base"
  cache_dir: null
data_args:
    dataset_name: "nicholasKluge/toxic-aira-dataset"
    dataset_split: "train"
    validation_split_percentage: 0.1
    streaming: false
    max_length: 512
    sanity_check: false
training_args:
  output_dir: "checkpoints"
  do_eval: true
  evaluation_strategy: "steps"
  save_strategy: "steps"
  logging_strategy: "steps"
  logging_steps: 1000
  max_steps: 10000
  save_steps: 1000
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 0.00005
  hub_token: null
  push_to_hub: true
  hub_model_id: "nicholasKluge/Aux-RewardModel"
extra_args:
  project_name: "Aira"
  wandb_token: null